### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by anureddy11**
Authrization flow, error handling, login/ signup, user table migration and model, validations

### CODE REVIEW

**Review by philling83 — CHANGES_REQUESTED** [review]
Add schema options to all migrations + seeders

**Comment by anureddy11** [comment]
> Add schema options to all migrations + seeders

done and pushed to dev

**Review by philling83 — CHANGES_REQUESTED** [review]
Make sure to use the options obj in your seeders as well

**Comment by anureddy11** [comment]
> Make sure to use the options obj in your seeders as well

Yes I already had that as part of my seeder file

**Review by philling83 — CHANGES_REQUESTED** [review]
I see you have the logic as far as creating the options obj but you don't pass it in in your bulkCreate function

**Comment by anureddy11** [comment]
> I see you have the logic as far as creating the options obj but you don't pass it in in your bulkCreate function

Ahh yes! just made the corrections

**Review by philling83 — CHANGES_REQUESTED** [review]
Rather than passing it in as a third argument, you will need to spread the validate obj with the options obj into one as a new key:value pair, rather than having them separate

**Comment by anureddy11** [comment]
> Rather than passing it in as a third argument, you will need to spread the validate obj with the options obj into one as a new key:value pair, rather than having them separate

I see. Made the changes.

**Review by philling83 — APPROVED** [review]
Naice 👍🏽

**Pull request merged**
